
import type {Metadata} from 'next';
import './globals.css';
import { AppProviders } from '@/contexts/AppProviders';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Speed Shop',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" />
      </head>
      <body className={cn("font-body antialiased", process.env.NODE_ENV === "development" ? "debug-screens" : "")}>
        <AppProviders>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
